// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdeysbnriwiwolgremsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkZXlzYm5yaXdpd29sZ3JlbXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MTY1NjIsImV4cCI6MjA2MzA5MjU2Mn0.pOAr4_PsCmhryGYSuBp9qeeg7HLXdm7KeFr_L98uXmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);